[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[runner]
# This will automatically rerun the app when files change
fastReruns = true
